<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-148C48N" failures="0" tests="10" name="testngFlag.Flag4" time="0.045" errors="1" timestamp="2022-06-04T18:02:52 IST" skipped="0">
  <testcase classname="testngFlag.Flag4" name="r" time="0.002"/>
  <system-out>
    <![CDATA[r]]>
  </system-out>
  <testcase classname="testngFlag.Flag4" name="m" time="0.002"/>
  <system-out>
    <![CDATA[m]]>
  </system-out>
  <testcase classname="testngFlag.Flag4" name="o" time="0.003"/>
  <system-out>
    <![CDATA[o]]>
  </system-out>
  <testcase classname="testngFlag.Flag4" name="b" time="0.014"/>
  <system-out>
    <![CDATA[b]]>
  </system-out>
  <testcase classname="testngFlag.Flag4" name="a" time="0.004"/>
  <system-out>
    <![CDATA[a]]>
  </system-out>
  <testcase classname="testngFlag.Flag4" name="g" time="0.003"/>
  <system-out>
    <![CDATA[g]]>
  </system-out>
  <testcase classname="testngFlag.Flag4" name="f" time="0.002"/>
  <system-out>
    <![CDATA[f]]>
  </system-out>
  <testcase classname="testngFlag.Flag4" name="q" time="0.003"/>
  <system-out>
    <![CDATA[q]]>
  </system-out>
  <testcase classname="testngFlag.Flag4" name="d" time="0.010">
    <error message="/ by zero" type="java.lang.ArithmeticException">
      <![CDATA[java.lang.ArithmeticException: / by zero
at testngFlag.Flag4.d(Flag4.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- d -->
  <system-out/>
  <testcase classname="testngFlag.Flag4" name="z" time="0.002"/>
  <system-out>
    <![CDATA[z]]>
  </system-out>
</testsuite> <!-- testngFlag.Flag4 -->
